language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4snapshot

env:
    matrix:
        - LARAVEL=5.5.* TESTBENCH=3.5.* PHPUNIT=6.* COMPOSER_FLAGS=""
        - LARAVEL=5.5.* TESTBENCH=3.5.* PHPUNIT=6.* COMPOSER_FLAGS="--prefer-lowest"
        - LARAVEL=5.8.* TESTBENCH=3.8.* PHPUNIT=7.* COMPOSER_FLAGS=""
        - LARAVEL=5.8.* TESTBENCH=3.8.* PHPUNIT=7.* COMPOSER_FLAGS="--prefer-lowest"
        - LARAVEL=6.*   TESTBENCH=4.*   PHPUNIT=8.* COMPOSER_FLAGS=""
        - LARAVEL=6.*   TESTBENCH=4.*   PHPUNIT=8.* COMPOSER_FLAGS="--prefer-lowest"

matrix:
    fast_finish: true
    exclude:
        - php: 7.1
          env: LARAVEL=6.*   TESTBENCH=4.*   PHPUNIT=8.*
    allow_failures:
        - php: 7.4snapshot

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - travis_retry composer self-update
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
