language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4snapshot

env:
    global:
        - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
    matrix:
        - LARAVEL=5.5.* TESTBENCH=3.5.* PHPUNIT=6.* COMPOSER_FLAGS=""
        - LARAVEL=5.5.* TESTBENCH=3.5.* PHPUNIT=6.* COMPOSER_FLAGS="--prefer-lowest"
        - LARAVEL=5.8.* TESTBENCH=3.8.* PHPUNIT=7.* COMPOSER_FLAGS=""
        - LARAVEL=5.8.* TESTBENCH=3.8.* PHPUNIT=7.* COMPOSER_FLAGS="--prefer-lowest"
        - LARAVEL=6.*   TESTBENCH=4.*   PHPUNIT=8.* COMPOSER_FLAGS=""
        - LARAVEL=6.*   TESTBENCH=4.*   PHPUNIT=8.* COMPOSER_FLAGS="--prefer-lowest"

matrix:
    fast_finish: true
    exclude:
        - php: 7.1
          env: LARAVEL=6.*   TESTBENCH=4.*   PHPUNIT=8.*
    allow_failures:
        - php: 7.4snapshot

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - travis_retry composer self-update
    - travis_retry composer install ${COMPOSER_FLAGS} --no-interaction
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

script:
    - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
    - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

branches:
    only:
        - master
